name: MengWhiteList
version: '${project.version}'
main: huanmeng.mengwhitelist.MengWhiteList
api-version: 1.16

commands:
  mwl_add:
    description: add the whitelist
  mwl_remove:
    description: remove the whitelist