name: MengWhiteList
version: '${project.version}'
main: top.huanmeng.MengWhiteList
api-version: 1.13
author: HuanMeng_
description: MengWhiteList - An efficient whitelist plugin
website: https://github.com/HuanMeng-official/MengWhiteList

commands:
  mwl_add:
    description: add the whitelist
  mwl_remove:
    description: remove the whitelist